version: "3.9"

services:
  audit:
    # Portainer will build from the repo’s Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    image: rfx-audit:latest       # tag written to local registry
    container_name: rfx-audit-v2
    ports:
      - "8085:3001"
    
    restart: unless-stopped
